// Generated file. Do not edit by hand.
// Do not edit this file by hand.

#pragma once

#include <cstdint>

namespace D2RL::Reimplementations {

inline constexpr uint16_t PublicOrdinalFirst = 2'000;
inline constexpr uint16_t PublicOrdinalLast  = 2'999;

enum class Stability : uint32_t {
	Supported      = 1,
	TargetSpecific = 2,
};

struct ExportInfo {
	const char* name;
	uint16_t    ordinal;
	Stability   stability;
};

using GetLevelIdFromUnitFn                                                   = int32_t(__fastcall*)(const void* unit) noexcept;
using GetLevelIdFromRoomContextFn                                            = int32_t(__fastcall*)(const void* roomContext) noexcept;
inline constexpr int32_t ItemHandednessOneHanded                             = 1;
inline constexpr int32_t ItemHandednessTwoHanded                             = 2;
inline constexpr int32_t ItemHandednessOneOrTwoHand                          = 3;
inline constexpr uint8_t ItemHandednessUseCharStatsPolicy                    = 0;
inline constexpr uint8_t ItemHandednessForceOneHandedPolicy                  = 1;
using GetItemHandednessForUnitFn                                             = int32_t(__fastcall*)(void* unit, void* item, uint8_t policy) noexcept;
inline constexpr uint32_t CanEquipItemPairEnforceCharStatsOffHandRestriction = 0x01;
using CanEquipItemPairFn                                                     = bool(__fastcall*)(void* unit, void* firstItem, void* secondItem, int32_t bodyLocation, uint32_t flags) noexcept;
using GenerateUnitCastIdFn                                                   = uint32_t(__fastcall*)(void* game) noexcept;
using SetUnitCastIdFn                                                        = void(__fastcall*)(void* unit, uint32_t castId) noexcept;
inline constexpr uint8_t GameVersionClassic                                  = 1;
inline constexpr uint8_t GameVersionLod                                      = 2;
inline constexpr uint8_t GameVersionRotw                                     = 3;
using TryGetMonumodConstantFn                                                = bool(__fastcall*)(uint8_t gameVersion, uint32_t rowId, int32_t* outValue) noexcept;
using CastAmplifyDamageFn                                                    = void(__fastcall*)(void* game, void* unit) noexcept;

inline constexpr ExportInfo GetLevelIdFromUnitInfo { "GetLevelIdFromUnit", 2'000, Stability::Supported };
inline constexpr ExportInfo GetLevelIdFromRoomContextInfo { "GetLevelIdFromRoomContext", 2'001, Stability::Supported };
inline constexpr ExportInfo GetItemHandednessForUnitInfo { "GetItemHandednessForUnit", 2'002, Stability::Supported };
inline constexpr ExportInfo CanEquipItemPairInfo { "CanEquipItemPair", 2'003, Stability::Supported };
inline constexpr ExportInfo GenerateUnitCastIdInfo { "GenerateUnitCastId", 2'004, Stability::Supported };
inline constexpr ExportInfo SetUnitCastIdInfo { "SetUnitCastId", 2'005, Stability::Supported };
inline constexpr ExportInfo TryGetMonumodConstantInfo { "TryGetMonumodConstant", 2'006, Stability::Supported };
inline constexpr ExportInfo CastAmplifyDamageInfo { "CastAmplifyDamage", 2'007, Stability::Supported };

static_assert(sizeof(Stability) == sizeof(uint32_t));

}
