#pragma once

#define D2RL_PLUGIN_MANIFEST_RESOURCE_ID 0x03E9
#define D2RL_PLUGIN_CONFIG_RESOURCE_ID   0x03EA

#define D2RL_PLUGIN_RESOURCE_DWORD_LITERAL(value) value##L
#define D2RL_PLUGIN_RESOURCE_DWORD(value)         D2RL_PLUGIN_RESOURCE_DWORD_LITERAL(value)
